In [ ]:
import numpy as np
my_arr= np.array((10,20,30,40))
my_arr[0]

10

In [ ]:
for i in my_arr:
  print (i)

10
20
30
40


In [ ]:
my_arr1= np.array([[10,20], [30,40]])

In [ ]:
my_arr1

array([[10, 20],
       [30, 40]])

In [ ]:
print(my_arr1.ndim)

2


In [ ]:
my_arr2= np.array([10,20,30,40,50,60])

In [ ]:
my_arr2[0:3]

[10, 20, 30]

In [ ]:
my_arr2[-3:]

[30, 40, 50]

In [ ]:
my_arr2[0:3]

[10, 20, 30]

In [ ]:
my_arr2[3:]

[40, 50]

In [ ]:
my_arr2[-3:-1]

[30, 40]

In [ ]:
my_arr2[-1]

50

In [ ]:
my_arr2[2:4]

[30, 40]

In [ ]:
my_arr2.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
my_arr2.reshape(-1)

array([10, 20, 30, 40, 50, 60])

In [ ]:
my_arr1.reshape(-1)

array([10, 20, 30, 40])

In [ ]:
a= np.array([[10,20,30]])

In [ ]:
a

array([[10, 20, 30]])

In [ ]:
b= np.array([[40,50,60]])

In [ ]:
b

array([[40, 50, 60]])

In [ ]:
c=np.concatenate((a,b))

In [ ]:
c

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
A= np.array([[10,20],[30,40]])

In [ ]:
A

array([[10, 20],
       [30, 40]])

In [ ]:
B= np.array([[50,60], [70,80]])

In [ ]:
B

array([[50, 60],
       [70, 80]])

In [ ]:
C= np.concatenate((A,B), axis=1)

In [ ]:
C

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])